### ISSUE TITLE
Can't compile with script/compile

### ISSUE THREAD

**Issue by nathansobo** [photoionization/cefode#7]
In file included from <built-in>:160:
<command line>:151:9: error: 'ENABLE_PRINTING' macro redefined [-Werror]
# define ENABLE_PRINTING 0

```
    ^
```

<command line>:24:9: note: previous definition is here
# define ENABLE_PRINTING 1

**Comment by zcbenz** [comment]
Fixed by https://github.com/zcbenz/cefode-chromium/commit/3f777b04db12726b700685ac1c0cd4463e7185bc
